vich_uploader:
    db_driver: orm
    mappings:
        file_invoice:
            uri_prefix: /images/invoices
            upload_destination: '%kernel.project_dir%/public/images/invoices'
            namer:  vich_uploader.namer_uniqid
            inject_on_load: true
            delete_on_update: false
            delete_on_remove: true