#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

#index:
#    path: /
#    controller: App\Controller\WelcomeController::index
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"